plugins:
  - name: protoc-gen-go
    implementation: golang:protobuf:protoc-gen-go
    deps:
      - "@org_golang_google_protobuf//proto"
      - "@org_golang_google_protobuf//reflect/protoreflect"
      - "@org_golang_google_protobuf//reflect/protoregistry"
      - "@org_golang_google_protobuf//runtime/protoimpl"
  - name: protoc-gen-go-grpc
    implementation: grpc:grpc-go:protoc-gen-go-grpc
    deps:
      - "@org_golang_google_grpc//:go_default_library"
      - "@org_golang_google_grpc//codes"
      - "@org_golang_google_grpc//status"
rules:
  - name: proto_compile
    implementation: stackb:rules_proto:proto_compile
    visibility:
      -  //visibility:public
  - name: proto_compiled_sources
    implementation: stackb:rules_proto:proto_compiled_sources
    visibility:
      -  //visibility:public
  - name: proto_go_library
    enabled: true
    implementation: stackb:rules_proto:proto_go_library
    visibility:
      -  //visibility:public
languages:
  - name: go
    plugins:
      - protoc-gen-go
      - protoc-gen-go-grpc
    rules:
      - proto_compile
      - proto_go_library
    enabled: false
